### ISSUE TITLE
Unexpected EOF; was expecting a close tag for element <mediawiki>

### ISSUE THREAD

**Issue by perrohunter** [bbende/solr-wikipedia#2]
When parsing the Wikimedia full dump (13GB~), seems like the file not starting with a proper document header <xml> tag but a <mediawiki> tag is confusing the parser. I'm getting exception 

com.ctc.wstx.exc.WstxEOFException: Unexpected EOF; was expecting a close tag for element <mediawiki>
 at [row,col {unknown-source}]: [46,0]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedEOF(StreamScanner.java:685)
	at com.ctc.wstx.sr.BasicStreamReader.throwUnexpectedEOF(BasicStreamReader.java:5519)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2722)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1073)
	at org.solr.wikipedia.iterator.WikiMediaIterator.hasNext(WikiMediaIterator.java:72)
	at org.solr.wikipedia.iterator.SolrInputDocIterator.hasNext(SolrInputDocIterator.java:30)
	at org.solr.wikipedia.indexer.DefaultIndexer.index(DefaultIndexer.java:73)
	at org.solr.wikipedia.indexer.DefaultIndexer.main(DefaultIndexer.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Any idea on how to turn around this? Will keep looking into it

**Comment by bbende** [comment]
Can you provide the beginning of the file you are trying to parse, up to line 47? The exception mentions (row,col) - (46,0) so I think that is line 46 of the file.

**Comment by perrohunter** [comment]
I think the issue is related to the enwiki-20151201-pages-articles-multistream.xml.bz2  file of the wikipedia dumps, it's indicated that each stream contains about 100 pages, so I'd assume the header tag would repeat

I switched to the non-multistream file enwiki-20151201-pages-meta-current1.xml-p000000010p000010000.bz2

Now I can read, but for some reason the revisions text is trimmed o_o  so now I'm checking on why could that be happening
